### PR TITLE
unit tests for stats

### PR DESCRIPTION
**Pull request by casche**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/reviewninja/review.ninja/pull/791" target="_blank">ReviewNinja

**Comment by casche** [comment]
@dfarr @fabianschwarzfritz any comments? Trying to get that test coverage back up..

**Comment by casche** [comment]
[Test coverage increased by 5%](https://coveralls.io/r/reviewninja/review.ninja?branch=feature%2Funit-test-stats)

**Comment by dfarr** [comment]
:+1:

**Pull request merged**
