### PR TITLE
Npm start now uses gulp serve

### PR DESCRIPTION
**Pull request by fabianschwarzfritz**
What do you guys think of that?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/reviewninja/review.ninja/pull/810" target="_blank">ReviewNinja

**Comment by dfarr** [comment]
I prefer we use gulp as an optional requirement (a task runner), not as something we require to bootstrap the application.

**Comment by dfarr** [comment]
This is also used by production to start the app. I will revert.

**Comment by fabianschwarzfritz** [comment]
Okay (y)

**Comment by gruiz17** [comment]
(y)

**Pull request merged**
