### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by dfarr**
A quick and easy docker compose solution to get a dev environment
up and running in no time. Should work fine in Linux environments
where docker-compose can bind to localhost. In other envs, the following
environment variables will need to be set/modified:
- GITHUB_CLIENT
- GITHUB_SECRET

You will need to create a new "GitHub developer application" with the following 
URLS, where HOST is the IP address:
- homepage: http://HOST:5000
- callback: http://HOST:5000/auth/github/callback

And set the GITHUB_CLIENT/GITHUB_SECRET to the provided values.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/reviewninja/review.ninja/pull/911" target="_blank">ReviewNinja

**Comment by MitchK** [comment]
Hm strange, why didn't the ninja set the status on the PR?

**Comment by flower-pot** [comment]
docker-compose is awesome .. +500

**Comment by dfarr** [comment]
Just waiting for docker-compose to support static IP addresses. When this is available there would be no customization required - just run `docker-compose up` and BOOM any contributor would be up and running!

We beed the static IP address so we can set the callback URL in the GitHub application.

**Comment by flower-pot** [comment]
Why does the hostname written in `/etc/hosts` not suffice?

**Comment by dfarr** [comment]
It's not accessible from your *local* machine. I think it may be possible to set up an nginx container pointing to the app container though...

**Comment by flower-pot** [comment]
If I understand correctly, isn't that rather a boot2docker issue rather than docker-compose? Because `HOST` would be your `DOCKER_HOST`, in my/our case that's the boot2docker vm.

**Comment by dfarr** [comment]
Yes. However I read that docker / compose will support specifying ips in the future, can't seem to find that issue now though....

**Comment by smazurov** [comment]
you can always [ngrok](https://ngrok.com/).
```yml
ngrok:
  image: centurylink/ngrok
  links:
    - web
  environment:
    HTTP_PORT: web:5000
```
Add above to `docker-compose.yml` and it will set up a tunnel for you.

You might need to wire it up in review-ninja to set up the right url for the webhooks. 

I doubt docker-compose will have this functionality built in anytime soon (or ever)

**Comment by dfarr** [comment]
Thanks @smazurov, will add this soon :+1:

**Comment by dfarr** [comment]
:+1:

**Pull request merged**
