### PR TITLE
Filter for Pending Pull Requests

### PR DESCRIPTION
**Pull request by casche**
see #683

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/reviewninja/review.ninja/pull/800" target="_blank">ReviewNinja

**Comment by casche** [comment]
FYI still in development, just using this PR for testing.

**Comment by casche** [comment]
Ok. I've added an additional 'filter' for pending pull requests. That is, pull requests that I've not ninja starred. 

screen shot 2015-03-06 at 11 00 02 am

screen shot 2015-03-06 at 11 00 08 am

**Comment by casche** [comment]
@dfarr you like the search better?

**Comment by dfarr** [comment]
I prefer filtering. With filtering the user can search for *anything*. However it's important we maintain the "clear filters" at the bottom as pagination and filtering cannot work in conjunction with each other.

**Comment by casche** [comment]
So we will go with #633 ?

**Comment by dfarr** [comment]
:+1:

**Pull request closed without merging**
